### ISSUE TITLE
Message is not string casting problem

### ISSUE THREAD

**Issue by gimasi** [er-jpg/logger_psql#1]
Hello,
Just started using your module - since we where looking for DB Logger...
First bug I've found is that sometimes the msg is a valid string... and we get an error even if it continues running..
We patched the logger_psql.ex, function insert_log like this...

 changeset =
      metadata
      |> Map.merge(%{
        level: to_string(level),
        time: DateTime.from_unix!(Keyword.get(md, :time), :microsecond),
        message: String.slice("#{inspect(msg)}",0,255),
        metadata: metadata
      })
      |> Log.changeset()

Massimo

**Comment by er-jpg** [comment]
Hello,

Thanks for using this library!

Thanks for letting me know, I'll try to patch this in this week itself, if you are in a hurry, feel free to open a merge request and I'll gladly review and merge it.
